# Generated by Django 5.2.1 on 2025-05-25 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_cliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
